services:
  db:
    image: postgres:${PG_VERSION:-16}
    restart: always
    env_file: postgres.env
    volumes:
      - ./db_scripts/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    ports:
      - ${DB_PORT:-5432}:5432

  redis:
    image: redis:${REDIS_VERSION:-7}
    restart: always
    command: redis-server
    ports:
      - ${REDIS_PORT:-6379}:6379
    volumes:
      - cache:/data

  rates-api:
    build:
      context: .
    env_file: app.prod.env
    ports:
      - ${APP_PORT:-80}:80
    depends_on:
      - db
      - redis

volumes:
  cache:
    driver: local
