services:
  db:
    image: postgres:${PG_VERSION}
    env_file: postgres.env
    volumes:
      - ./db_scripts/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    ports:
      - ${DB_PORT}:5432

  rates-api:
    build:
      context: .
    env_file: app.prod.env
    ports:
      - ${APP_PORT}:80
    depends_on:
      - db
